[book]
title = "molex"
description = "Molecular structure conversion library"
authors = ["Andreas Petrides"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/petridecus/molex"
